### ISSUE TITLE
console.log prints the argument, but also undefined in the same spot

### ISSUE THREAD

**Issue by bobby29831** [LeoDog896/jsnow#1]
![image](https://user-images.githubusercontent.com/84546230/153770253-5520673c-d68c-4588-afd7-48cb4e28333e.png)
As you can see here, console.log() returns undefined which makes sense.

However, once you add an argument to be sent to the config, both values, the argument that has been printed out and the return value (undefined) show on top of each other.
![image](https://user-images.githubusercontent.com/84546230/153770304-e60610d6-12c6-4324-bcd6-76f7a4167261.png)

**Comment by LeoDog896** [comment]
Thanks for the first issue! I can only assume it's wrapping the input, showing it, and showing it once again due to console.log. I'll prepare a fix once I arrive home.

**Comment by LeoDog896** [comment]
It seems that somewhere along the line I fixed it. Thanks for your issue though!
